### ISSUE TITLE
Panic triggered by conflicting CLI switches

### ISSUE THREAD

**Issue by ryzhyk** [Kixiron/ddshow#11]
It appears that `--differential` and `--replay-logs` flags are mutually exclusive, but instead of returning an error message to that effect ddshow panics. Also it is not clear from the documentation that `--differential` (and other flags) are only meaningful in the network mode.

```
lryzhyk@nerpa:~/projects/differential-datalog/java/test$ ddshow --differential --replay-logs timely_trace/
[0s] Loading Timely replay from timely_trace/: loaded 2 replay files
thread 'main' panicked at 'the differential listener should be created when `args.differential_enabled` is true', src/replay_loading.rs:151:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kixiron** [comment]
This was a bug, I believe I fixed it with some local stuff that I hadn't pushed yet, can you try latest master?

**Comment by ryzhyk** [comment]
Yep, that solved it.  `--differential` now has the effect of enabling the replay of the differential trace if it happens to exist in the same directory.
